### ISSUE TITLE
Hyper 1.0

### ISSUE THREAD

**Issue by ibraheemdev** [ibraheemdev/astra#13]
Upgrade to Hyper 1.0, look into what extra features we can implement now (timers, etc.).

**Comment by ibraheemdev** [comment]
Hi, I'm a little crunched for time at the moment. I do plan to upgrade to Hyper 1.0 at some point, unfortunately I can't give you a concrete timeline. Also happy to review and accept a PR :)

**Comment by libvoid** [comment]
Oooh! That's nice! Thank you @ibraheemdev! :)

**Comment by dpc** [comment]
Hey, I just noticed there's a new release. Just wanted to leave some voice of support and appreciation.
