### ISSUE TITLE
Feature suggestion: client address of requests

### ISSUE THREAD

**Issue by Palladinium** [ibraheemdev/astra#2]
I'm in the process of migrating some code from using `tiny_http` to `astra`, but there's one piece of functionality I've been relying upon (mainly for logging) that I don't think `astra` supports at the moment: getting the client address of a request.

In `tiny_http`, that's provided by its `Request` type [remote_addr()](https://docs.rs/tiny_http/latest/tiny_http/struct.Request.html#method.remote_addr), and plain `hyper` gives access to it through `MakeService` [(see this commit)](https://github.com/hyperium/hyper/commit/9d45e15eec37d92d2c352178f80a2630383d22eb).

I'd imagine this would require a breaking change to `astra::Service` to accept a second argument or an entirely new type of `Request`. I'm happy to push a PR if this sounds like a good idea.

**Comment by ibraheemdev** [comment]
Another option is storing it in the request extensions.. but that would require a few extra allocations. I would accept a PR adding a `ConnectInfo` type that stores the remote address as a second argument to `Service`.

**Comment by ibraheemdev** [comment]
Sorry for the delay, this was released as part of 0.2.0.
