### ISSUE TITLE
`Arc` the `Service` internally is not optimal

### ISSUE THREAD

**Issue by dpc** [ibraheemdev/astra#4]
https://github.com/ibraheemdev/astra/blob/53ad0859de7a1e2af90d8ae1a6666c9a7a276c03/src/server.rs#L149

`Service` already requires `Send + Sync + 'static` so it's rather pointless. Instead `S: Service + Clone`, and the user can `Arc` (or not) the `S` internally.

In my case I need to use `Arc` internally in my code (because reasons), and now it will be effectively `Arc<Arc<Stuff>>` and it can't be avoided, so my inner micro-optimizator is bothering me.

**Comment by ibraheemdev** [comment]
Resolved by #5.
